import 'package:flutter/material.dart';

List festlist = [
  {
    'Festival': 'Makar Sakranti',
    'word': 'Create your Makar Sakranti Templates',
    'Image': 'assets/maker_sankrti/img_4.1_cleanup.jpg',
    'Color': Colors.red,
    'images': [
      'aasets/img/mahashivratri/1.jpg',
      'aasets/img/mahashivratri/2.jpg',
      'aasets/img/mahashivratri/3.jpg',
      'aasets/img/mahashivratri/4.jpg',
      'aasets/img/mahashivratri/5.jpg'
    ],
  },
  {
    'Festival': 'Raksha Bandhan',
    'word': 'Create your Raksha Bandhan Templates',
    'Image': 'assets/raksha_bandhan/img_3.1.jpg',
    'Color': Colors.yellow,
    'images': [
      'aasets/img/rakshabandhan/1.jpg',
      'aasets/img/rakshabandhan/2.jpg',
      'aasets/img/rakshabandhan/3.jpg',
      'aasets/img/rakshabandhan/4.jpg',
      'aasets/img/rakshabandhan/5.jpg',
    ],
  },
  {
    'Festival': 'Basant Panchami',
    'word': 'Create your Basant Panchami Templates',
    'Image': 'assets/Basnt_panchami/img1.jpg',
    'Color': Colors.blue,
    'images': [
      'aasets/img/basantpanchami/1.jpg',
      'aasets/img/basantpanchami/2.jpg',
      'aasets/img/basantpanchami/3.jpg',
      'aasets/img/basantpanchami/4.jpg',
      'aasets/img/basantpanchami/5.jpg',
    ],
  },
  {
    'Festival': 'Diwali',
    'word': 'Create your Diwali Templates',
    'Image': 'assets/Diwali/img_2.1.jpg',
    'Color': Colors.redAccent,
    'images': [
      'aasets/img/diwali/1.jpg',
      'aasets/img/diwali/2.jpg',
      'aasets/img/diwali/3.jpg',
      'aasets/img/diwali/4.jpg',
      'aasets/img/diwali/5.jpg',
      'aasets/img/diwali/6.jpg',
    ],
  },
  {
    'Festival': 'Pongal',
    'word': 'Create your Pongal Templates',
    'Image': 'assets/pogal/img1.jpg',
    'Color': Colors.purple,
    'images': [
      'aasets/img/pongal/1.jpg',
      'aasets/img/pongal/2.jpg',
      'aasets/img/pongal/3.jpg',
      'aasets/img/pongal/4.jpg',
      'aasets/img/pongal/5.jpg',
    ],
  },
  {
    'Festival': 'Maha Shivratri',
    'word': 'Create your Maha Shivratri Templates',
    'Image': 'assets/maha_shivratri/img1.jpg',
    'Color': Colors.brown,
    'images': [
      'aasets/img/makarsakranti/1.jpg',
      'aasets/img/makarsakranti/2.jpg',
      'aasets/img/makarsakranti/3.jpg',
      'aasets/img/makarsakranti/4.jpg',
      'aasets/img/makarsakranti/5.jpg',
    ],
  },
  {
    'Festival': 'Bhai dooj',
    'word': 'Create your Bhai dhuj Templates',
    'Image': 'assets/bhai_dooj/img1.jpg',
    'Color': Colors.pink,
    'images': [
      'aasets/img/bhaidooj/1.jpg',
      'aasets/img/bhaidooj/2.jpg',
      'aasets/img/bhaidooj/3.jpg',
      'aasets/img/bhaidooj/4.jpg',
      'aasets/img/bhaidooj/5.jpg',
    ],
  },
  {
    'Festival': 'Holi',
    'word': 'Create your holi Templates',
    'Image': 'assets/holi/img_5.1.jpg',
    'Color': Colors.lightGreen,
    'images': [
      'aasets/img/holi/1.jpg',
      'aasets/img/holi/2.jpg',
      'aasets/img/holi/3.jpg',
      'aasets/img/holi/4.jpg',
      'aasets/img/holi/5.jpg',
    ],
  },
  {
    'Festival': 'Independence Day',
    'word': 'Create your Independence Day Templates',
    'Image': 'assets/indpened_day/day_cleanup.jpg',
    'Color': Colors.orangeAccent,
    'images': [
      'aasets/img/independenceday/1.jpg',
      'aasets/img/independenceday/2.jpg',
      'aasets/img/independenceday/3.jpg',
      'aasets/img/independenceday/4.jpg',
      'aasets/img/independenceday/5.jpg',
    ],
  },
  {
    'Festival': 'Republic Day',
    'word': 'Create your Republic Day Templates',
    'Image': 'assets/republic_day/img1_cleanup.jpg',
    'Color': Colors.black54,
    'images': [
      'aasets/img/republicday/1.jpg',
      'aasets/img/republicday/2.jpg',
      'aasets/img/republicday/3.jpg',
      'aasets/img/republicday/4.jpg',
      'aasets/img/republicday/5.jpg',
    ],
  },
  {
    'Festival': 'Navratri',
    'word': 'Create your Navratri Templates',
    'Image': 'assets/navratri/img1.jpg',
    'Color': Colors.red,
    'images': [
      'aasets/img/navratri/1.jpg',
      'aasets/img/navratri/2.jpg',
      'aasets/img/navratri/3.jpg',
      'aasets/img/navratri/4.jpg',
      'aasets/img/navratri/5.jpg',
      'aasets/img/navratri/6.jpg',
    ],
  },
  {
    'Festival': 'Ganesh Chaturthi',
    'word': 'Create your Ganesh Chaturthi Templates',
    'Image': 'assets/genesh_chaturtiy/img_1.1.png',
    'Color': Colors.deepOrange,
    'images': [
      'aasets/img/ganeshchaturthi/1.jpg',
      'aasets/img/ganeshchaturthi/2.jpg',
      'aasets/img/ganeshchaturthi/3.jpg',
      'aasets/img/ganeshchaturthi/4.jpg',
      'aasets/img/ganeshchaturthi/5.jpg',
    ],
  },
];
